# Generated by Django 4.2 on 2024-03-12 16:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_members_former_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='introduction_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
