# Generated by Django 4.2 on 2024-01-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='feature',
            new_name='featured',
        ),
    ]
