# Generated by Django 4.2 on 2024-01-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_rename_feature_publication_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.URLField(default=True),
            preserve_default=False,
        ),
    ]
