# Generated by Django 4.2 on 2024-01-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_publication_next_page_publication_previous_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='next_page',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='previous_page',
        ),
    ]
